### PR TITLE
Plotly.js renderer component

### PR DESCRIPTION
**Pull request by alex-ketch**
Some useful resources/references @nokome :
- https://stenciljs.com/docs/component-lifecycle#componentwillload
- Alternating between static encoded HTML and rendering Schema JSON is a little annoying. Example can be seen in [`NodeList`](https://github.com/stencila/designa/blob/11abcd942301e19fa3f779fd7b4d1ea9e5c2b556/packages/components/src/components/nodeList/nodeList.tsx#L96-L112) component and the [`Code` components](https://github.com/stencila/designa/blob/11abcd942301e19fa3f779fd7b4d1ea9e5c2b556/packages/components/src/components/codeExpression/codeExpression.tsx#L197-L245)
- To build:
  - `npm install`, `npm run bootstrap`, in two separate terminals `npm run build:watch -- --scope "@stencila/components"` and `npm run storybook`. Draft example is in the `Node List/Multiple Nodes` story.

### CODE REVIEW

**Comment by nokome** [comment]
@alex-ketch I have taken this as far as I usefully can I think. Basics are working but needs refinement esp re HTML hydration.

You will note some refactoring (e.g renaming the component class to be more consistent with others etc). Also, I have changed the HTML encoding to the following to try to get the hydration from HTML working but have not had success with that. Would appreciate it if you could take this over.

```html
  <stencila-image-plotly>
    <script slot="data" type="application/vnd.plotly.v1+json">${plotlyData}</script>
    <img src="https://via.placeholder.com/150">
  </stencila-image-plotly>
```

**Comment by alex-ketch** [comment]
@nokome I've finished up the remaining tasks, but want to sync up and confirm the structure of the markup across here and Encoda before we merge this PR.
The changes I've made should allow passing just the `data` array, as well as the full configuration object to Plotly.

**Comment by nokome** [comment]
Thanks @alex-ketch . Looks good, but the stories aren't working for me e.g.

image

Can't make sense of where that "Plotly placeholder element" is coming from.

**Comment by alex-ketch** [comment]
odd… Have you re-built the components with the latest changes @nokome?

**Comment by nokome** [comment]
Yeah, I have, but I think there were errors. Don't worry about it, if it's all working OK for you, I'm happy for us to go ahead and merge this and I'll make the necessary changes in Encoda.

**Review by nokome — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
